services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: music
      POSTGRES_DB: music_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music -d music_app"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://music:music@db:5432/music_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5600:5600"
    restart: unless-stopped

volumes:
  pgdata: